#!/usr/bin/env python3
"""Generate a ready-to-run NLTE pipeline config so you don't hand-write one.

The generated config uses the single switch (``grid.synthesis.calculation_mode:
"NLTE"``) and fills in absolute paths to the model atmospheres, line lists and
(for the binary workflow) checks the NLTE species map. After writing it the tool
runs the same NLTE preflight the pipeline uses, so you immediately see whether
anything is still missing.

    # binary departure grids (default)
    python3 scripts/init_nlte_config.py --output configs/pipeline/config_nlte.json

    # also repoint DATA/SPECIES_LTE_NLTE.dat at your downloaded data (backs up .bak)
    python3 scripts/init_nlte_config.py --output configs/pipeline/config_nlte.json --fix-species-map

    # ASCII per-abundance departures
    python3 scripts/init_nlte_config.py --output configs/pipeline/config_nlte.json \
        --workflow ascii --ascii-dir DATA/DEP/nlte_departures_ascii --species Fe
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from typing import Any, Dict, List, Tuple

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))

if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

from nlte_config import default_nlte_info_file, preflight_nlte_from_config  # noqa: E402

_DEFAULT_LINELIST = "nlte_ges_linelist_jmg16jan2026_I_II"
_MODEL_ATM = os.path.join(REPO_ROOT, "input_files", "model_atmospheres", "1D", "marcs_standard_comp")
_LINELIST_DIR = os.path.join(REPO_ROOT, "input_files", "linelists")
_NLTE_MODEL_ATOMS = os.path.join(REPO_ROOT, "input_files", "nlte_data", "model_atoms")
_NLTE_DEP_GRIDS = os.path.join(REPO_ROOT, "input_files", "nlte_data", "departure_grids")


def _detect_linelist() -> str:
    """Pick a real line list from input_files/linelists, else the usual default."""
    if os.path.isdir(_LINELIST_DIR):
        candidates = sorted(
            f for f in os.listdir(_LINELIST_DIR)
            if not f.startswith(".") and os.path.isfile(os.path.join(_LINELIST_DIR, f))
        )
        preferred = [f for f in candidates if "linelist" in f.lower()] or candidates
        if preferred:
            return preferred[0]
    return _DEFAULT_LINELIST


def _build_config(args: argparse.Namespace) -> Dict[str, Any]:
    cfg: Dict[str, Any] = {
        "_comment": (
            "Generated by scripts/init_nlte_config.py. NLTE is the single switch: "
            "grid.synthesis.calculation_mode='NLTE' turns it on; nlte.enabled and the "
            "info file are derived/defaulted. Re-check anytime with "
            "scripts/validate_nlte_config.py."
        ),
        "grid": {
            "grid_version": "nlte-generated-v1",
            "sampling": "grid",
            "axes": {"teff": args.teff, "logg": args.logg, "feh": args.feh, "turbvel": "01"},
            "synthesis": {
                "lam_min": args.lam_min,
                "lam_max": args.lam_max,
                "lam_step": args.lam_step,
                "output_mode": "Flux",
                "calculation_mode": "NLTE",
            },
        },
        "turbospectrum": {
            "compiler": args.compiler,
            "paths": {
                "model_atmosphere_path": _MODEL_ATM,
                "linelist_path": _LINELIST_DIR,
                "linelist_files": [_detect_linelist()],
            },
        },
        "outputs": {"run_root": args.run_root},
        "runtime": {"workers": None, "chunk_rows": 64},
    }
    if args.workflow == "ascii":
        ascii_dir = os.path.abspath(args.ascii_dir)
        cfg["nlte_ascii_departures"] = {
            "directory": ascii_dir,
            "species": args.species,
            "abundance_column": "feh",
            "abundance_scale": "relative",
            "match": "nearest",
        }
    return cfg


def _patch_species_map(path: str, model_dir: str, dep_dir: str) -> Tuple[List[Tuple[int, str, str]], str]:
    """Repoint the two path headers in a SPECIES_LTE_NLTE.dat (returns changes + backup path)."""
    with open(path, "r", encoding="utf-8") as handle:
        lines = handle.readlines()
    changes: List[Tuple[int, str, str]] = []
    for idx, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("# path for model atom files") and idx + 1 < len(lines):
            changes.append((idx + 1, lines[idx + 1].rstrip("\n"), model_dir))
            lines[idx + 1] = model_dir + "\n"
        elif stripped.startswith("# path for departure files") and idx + 1 < len(lines):
            changes.append((idx + 1, lines[idx + 1].rstrip("\n"), dep_dir))
            lines[idx + 1] = dep_dir + "\n"
    backup = path + ".bak"
    shutil.copy2(path, backup)
    with open(path, "w", encoding="utf-8") as handle:
        handle.writelines(lines)
    return changes, backup


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output", required=True, help="Path to write the generated NLTE config JSON")
    parser.add_argument("--workflow", choices=("binary", "ascii"), default="binary",
                        help="binary departure grids (default) or ASCII per-abundance departures")
    parser.add_argument("--ascii-dir", default=None, help="ASCII departure directory (required for --workflow ascii)")
    parser.add_argument("--species", default="Fe", help="NLTE species for the ASCII workflow (default: Fe)")
    parser.add_argument("--run-root", default=os.path.join(REPO_ROOT, "runs", "nlte"), help="Output run_root")
    parser.add_argument("--teff", default="5000,5500", help="Teff axis (default: 5000,5500)")
    parser.add_argument("--logg", default="4.0,4.5", help="logg axis (default: 4.0,4.5)")
    parser.add_argument("--feh", default="-0.5,0.0", help="[Fe/H] axis (default: -0.5,0.0)")
    parser.add_argument("--lam-min", type=float, default=5000.0)
    parser.add_argument("--lam-max", type=float, default=5200.0)
    parser.add_argument("--lam-step", type=float, default=0.01)
    parser.add_argument("--compiler", default="gf", choices=("gf", "intel"))
    parser.add_argument("--force", action="store_true", help="Overwrite the output config if it already exists")
    parser.add_argument("--fix-species-map", action="store_true",
                        help="Repoint DATA/SPECIES_LTE_NLTE.dat at input_files/nlte_data/* (writes a .bak first)")
    parser.add_argument("--skip-preflight", action="store_true", help="Do not run the NLTE preflight after writing")
    args = parser.parse_args()

    if args.workflow == "ascii" and not args.ascii_dir:
        parser.error("--workflow ascii requires --ascii-dir")

    output = os.path.abspath(args.output)
    if os.path.exists(output) and not args.force:
        parser.error(f"{output} already exists (use --force to overwrite)")

    cfg = _build_config(args)
    os.makedirs(os.path.dirname(output) or ".", exist_ok=True)
    with open(output, "w", encoding="utf-8") as handle:
        json.dump(cfg, handle, indent=2)
        handle.write("\n")
    print(f"Wrote NLTE config: {output}")

    # Heads-up about inputs that the config points at but that are not present yet.
    if not os.path.isdir(_MODEL_ATM):
        print(f"  note: model atmospheres not found at {_MODEL_ATM} (download_data.sh --atmospheres MARCS)")
    if args.workflow == "binary" and not (os.path.isdir(_NLTE_MODEL_ATOMS) and os.path.isdir(_NLTE_DEP_GRIDS)):
        print(f"  note: NLTE data not found under {os.path.dirname(_NLTE_MODEL_ATOMS)} (download_data.sh --nlte-atoms all)")

    # Optionally repoint the species map at the downloaded data.
    if args.fix_species_map and args.workflow == "binary":
        species_map = default_nlte_info_file(REPO_ROOT)
        if not os.path.isfile(species_map):
            print(f"  --fix-species-map: {species_map} not found; nothing to patch.")
        else:
            changes, backup = _patch_species_map(species_map, _NLTE_MODEL_ATOMS, _NLTE_DEP_GRIDS)
            print(f"Patched {species_map} (backup: {backup}):")
            for _, old, new in changes:
                print(f"    {old}  ->  {new}")
    elif args.fix_species_map:
        print("  --fix-species-map only applies to the binary workflow; ignored.")

    if args.skip_preflight:
        return 0

    result = preflight_nlte_from_config(cfg, config_dir=os.path.dirname(output), project_root=REPO_ROOT)
    print(f"\nPreflight ({'ASCII departures' if result['workflow'] == 'ascii' else 'binary departure grids'}):")
    if not result["problems"]:
        print("  OK: NLTE inputs look runnable.")
        rel = os.path.relpath(output, REPO_ROOT)
        shown = output if rel.startswith("..") else rel
        print(f"\nNext:  python3 scripts/pipeline_from_config.py --config {shown}")
        return 0
    for line in result["problems"]:
        print(f"  {line}" if line else "")
    print("\nResolve the above (e.g. download data and/or re-run with --fix-species-map), then run the pipeline.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
